/**
 * Shared runtime configuration that is safe to commit.
 * Fields follow the structure of the Volc StartVoiceChat payload
 * (ASRConfig / TTSConfig / LLMConfig, etc.) for easier copy-and-paste.
 */
import type { RuntimeConfig } from './types'

const semanticInterruptKeywords = [
  '暂停',
  '暂停一下',
  '停止',
  '停一下',
  '先停一下',
  '先别说',
  '别说了',
  '别继续',
  '打断',
  '打住',
  '可以了',
  '好了',
  '够了',
  '下一个',
  '下一项',
  '换一个',
  '我知道了',
  '谢谢',
  '收到',
  '知道了',
  '不用了',
  '行了',
  '先这样',
  '听到了',
  '听够了',
  '等一下',
  '稍等一下',
  '别说话',
  '不用继续',
  '够啦',
  '停下',
  '不想听了',
  '故事先这样',
  '先讲到这里',
  '换个话题',
  '后面不用说了',
  '休息一下',
  '我累了',
  '先停一会儿',
  '可以换别的',
  '不用重复',
  '我知道接下来',
  '先告一段落',
  '到此为止',
  '别讲故事了',
  '先聊别的',
  '停一停',
  '静一下',
  '安静一下',
  '冷静一下',
  'quiet please',
  'stop talking',
  'that is enough',
  'no more',
  'all good',
  'we are good',
  'you can pause',
  'please wait',
  'i am good',
  'i heard enough',
  'tell me later',
  'change topic',
  'not interested',
  'story can stop',
  'take a break',
  'let us pause',
  'Stop',
  'Hold on',
  'Pause',
  'Wait',
  'Enough',
  'Next one',
  'You can stop now',
] as const

const semanticHotwordContext = JSON.stringify({
  hotwords: semanticInterruptKeywords.map((word) => ({ word })),
})

export const runtimeConfig: RuntimeConfig = {
  scene: {
    taskId: 'emq-aigc-task-001',
    icon: 'https://lf3-rtc-demo.volccdn.com/obj/rtc-aigc-assets/DoubaoAvatar.png',
    name: 'EMQ 陪伴助手',
    defaultSceneId: 'emq-mcp-ai-companion',
  },
  agent: {
    userId: 'emq-ai-bot',
    welcomeMessage: '嗨～我是 EMQ，很高兴见到你！',
    enableConversationStateCallback: true,
    ansMode: 3,
    voiceprintMode: 1,
  },
  interrupts: {
    mode: 0,
    speechDuration: 400,
    silenceTime: 600,
    volumeGain: 0.5,
    keywords: [...semanticInterruptKeywords],
  },
  asrConfig: {
    Provider: 'volcano',
    ProviderParams: {
      Mode: 'smallmodel',
      Cluster: 'volcengine_streaming_common',
      context: semanticHotwordContext,
    },
    VADConfig: {
      SilenceTime: 600,
    },
    VolumeGain: 0.5,
    TurnDetectionMode: 0,
  },
  ttsConfig: {
    Provider: 'volcano',
    Cluster: 'volcano_tts',
    Mode: 'standard',
    VoiceType: 'BV033_streaming',
    SpeedRatio: 1.2,
    PitchRatio: 1.1,
    VolumeRatio: 1,
    SpeechRatio: 0.8,
    PitchRate: 0,
    SpeechRate: 0.4,
    Emotion: 'happy',
    EmotionIntensity: 0.8,
    IgnoreBracketText: [],
    DisableMarkdownFilter: false,
    EnableLatexTn: false,
  },
  llmConfig: {
    Mode: 'CustomLLM',
    EndpointId: '',
    SystemMessage: '',
    VisionEnable: false,
    ModelName: 'qwen-flash',
    Temperature: 0.5,
    TopP: 0.9,
    MaxTokens: 256,
    HistoryLength: 15,
    EnableRoundId: true,
    UserPrompts: [
      { Role: 'assistant', Content: '嗨～我是 EMQ，很高兴见到你！' },
      { Role: 'user', Content: '你好' },
    ],
    StreamOptions: { include_usage: true },
    ExtraHeaders: undefined,
  },
  api: {
    region: 'cn-north-1',
    version: '2024-12-01',
  },
}
